# Site settings
title: Jesse Moore
description: 'Data Scientist, Data Analyst, Business Leader, and Entry-Level Dad'
url: 'http://jessemoore.ca'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jesse Moore'
  email: jessemoore07@gmail.com
  twitter_username: macroinv
  # facebook_username: joshgerdes
  github_username:  jes-moore
  linkedin_username:  jessemoore07

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
